import type { Metadata } from "next";
import { Geist, Geist_Mono,Press_Start_2P } from "next/font/google";
import "./globals.css";
import NavBar from "./src/components/NavBar";
import Footer from "./src/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pressStart = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",     
  variable: "--font-pressstart",
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ezerfr",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} ${pressStart.variable} antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
